PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
 
#Display everything available from the query
SELECT *

WHERE {

#Define the Primary Subject: return all skos Concepts in the graph and their preferred labels. 
#? defines the label used in the return for skos:concept (the subject),
#skos:preflabel the other thing(s) we want directly against the subject,
# and '.' closes out this subject within the query.
?concepturi a skos:Concept ;
skos:prefLabel ?preflabel .

#Set Optional returns (to ignore sparql null rule), i.e. return blank instead of preventing result
OPTIONAL {?concepturi skos:definition ?definition}. #optional definitions
OPTIONAL {?concepturi skos:notation ?notation} . #optional notations

#Apply filters
FILTER(LANG(?preflabel)="en") #restrict to results with an english language label
}

#Display in order of: the uri of the concept
ORDER BY ?concepturi
